# Temporary stub hardware config for home-server.
# Replace this with the real autogenerated file from `nixos-generate-config`
# once the machine is set up.
#
# This exists so `nix flake check` can evaluate `nixosConfigurations.home-server`
# without failing NixOS filesystem assertions.

{ lib, ... }:

{
  # Minimal required root filesystem to satisfy NixOS evaluation.
  # The device path is a placeholder; adjust when installing.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  swapDevices = [ ];

  # Satisfy NixOS bootloader assertions during evaluation.
  # "nodev" means "don't install to any block device" (placeholder for now).
  boot.loader.grub.devices = [ "nodev" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
